language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 3
- name: DIETClassifier
  epochs: 10
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 10
policies:
- name: AugmentedMemoizationPolicy
  max_history: 2
- name: TEDPolicy
  epochs: 15
  max_history: 2
- name: RulePolicy
